<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXd8gtd5\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXd8gtd5/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerXd8gtd5.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerXd8gtd5\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerXd8gtd5\appProdProjectContainer([
    'container.build_hash' => 'Xd8gtd5',
    'container.build_id' => 'eea8c08b',
    'container.build_time' => 1565579006,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXd8gtd5');
