<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6qd8jqd\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6qd8jqd/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container6qd8jqd.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container6qd8jqd\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container6qd8jqd\appDevDebugProjectContainer([
    'container.build_hash' => '6qd8jqd',
    'container.build_id' => '01d269fe',
    'container.build_time' => 1565325487,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6qd8jqd');
